name: Webwriter

on:
  push:
    paths:
      - ".github/workflows/generate-webwriter.yml"
      - ".github/actions/build-ttf/action.yml"
      - "raw/**"

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  ##### ===========================
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build-ttf
        with:
          weight: 0
          strict: nostrict
          filename-prefix: "sakamata-jtc-font"

  ##### ===========================
  gen-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run chart-generator
        run: |
          cd builder/chart-generator
          dotnet run --rawdir ../../raw

      - uses: actions/upload-artifact@v3
        with:
          name: generated-charts
          path: builder/chart-generator/output/*

  ##### ===========================
  build-webfont:
    runs-on: ubuntu-latest
    needs:
      - build
      - gen-chart

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sakamata-jtc-font-0-nostrict
          path: fonts

      - uses: actions/download-artifact@v3
        with:
          name: generated-charts
          path: ~/artifact/chart

      - name: Install woff2
        run: sudo apt-get install -y woff2

      - name: Compress to woff2
        run: |
          woff2_compress fonts/sakamata-jtc-font-0-nostrict.ttf

      - uses: actions/upload-artifact@v3
        with:
          name: webfont
          path: fonts/*.woff2

      - name: Copy data
        run: |
          mkdir toupload
          cp fonts/*.woff2 toupload/
          cp fonts/*.sources.tsv toupload/
          cp ~/artifact/chart/char.tsv toupload/sakamata-jtc-font-char.tsv

      - name: Deploy font files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          username: ${{ secrets.BLOB_UPLOAD_USER }}
          server: ${{ secrets.BLOB_UPLOAD_HOST }}
          ssh_private_key: ${{ secrets.BLOB_SFTP_KEY }}
          sftp_only: true
          local_path: "./toupload/*"
          remote_path: "/home/${{ secrets.BLOB_UPLOAD_USER }}/domains/07b8f021-4a5b-4903-bb58-1f3e540a4eb6.contentdelivernet.com/public_html/font.sakamata.ch/jtc/"
